---
title: "Unsupervised alignment"
author: "Maël Delem"
# code
code-fold: false
code-annotations: hover
warning: false
error: false
message: false
---

::: {.callout-note collapse="true"}
# Packages and setup

Down below is the code to load necessary packages used for the simulation and analysis, along with some setups for the whole document (*hover over the numbers on the far right for additional explanation of code and mechanics*).

```{r setup}
#| output: false
#| echo: true

# ═══ Packages ═════════════════════════════════════════════════════════════════

if (!require(librarian)) install.packages(librarian) # <1>
library(librarian) # <1>

# now putting packages on our library's shelves:
shelf(
  # ─── data management ─────────────────
  holodeck,       # simulating multivariate data
  cluster,        # dissimilarity matrices
  
  # ─── modelling ───────────────────────
  mclust,         # mixture clustering
  
  #  data visualization ──────────────
  # palettes
  viridis,        # colour-blind friendly palettes
  # interactive
  plotly,         # interactive plots
  ggdendro,       # dendrograms
  seriation,      # dissimilarity plots
  webshot2,       # HTML screenshots for Word render
  webshot,
  
  # ─── essential package collections ───
  doParallel,     # parallel execution
  easystats,      # data analysis ecosystem
  reticulate,     # R to Python                  # <2>
  tidyverse,      # modern R ecosystem
)

# ─── Global cosmetic theme ───
theme_set(theme_modern(base_size = 14))

pal_okabe_ito <- c(                                                        # <3>
  "#E69F00", "#56B4E9", "#009E73",                            
  "#F5C710", "#0072B2", "#D55E00", "#CC79A7", "#6c0009")      

# We'll need 9 colors at some point
pal_okabe_ito_extended <- c(                                 
  "#E69F00", "#56B4E9", "#009E73",                           
  "#F5C710", "#0072B2", "#D55E00", "#CC79A7", "#6c0009", "#414487FF")

# We'll need 30 colors at another moment
cool_30_colors <- c(                                                   
  "#3d51b4", "#414487FF", "#003d73", "#440154FF", "#6c0009", "#b64e4e",
  "#D55E00", "#E69F00", "#F5C710", "#FDE725FF", "#f2bb7b", "#f1afad", "#CC79A7", 
  "#e57774", "#7AD151FF", "#57b571", "#318a4a", "#009E73", "#22A884FF", 
  "#2A788EFF", "#0072B2", "#2da6b5", "#56B4E9", "#889be0", "#6677e0",   
  "#3d51b4", "#414487FF", "#003d73", "#440154FF", "#6c0009", "#b64e4e"  
  )                                                                        # <3>
```
1.  The package `librairian` eases package management with the "shelf" function, which automatically: (1) checks if a package is installed; (2) installs it if need be; (3) loads the package like the "library()" function would.
2.  `reticulate` allows to translate and transfer objects and functions from R to Python and vice-versa, and was thus of primary importance for the successful use of the Python toolbox on our simulated data.
3.  These are personal custom color palettes meant to extend my favourite palette, the color-atypical friendly Okabe-Ito color palette. The palette originally has only eight colors, but I will need nine, then up to 30 for later graphs, so I extended it with a hand-picked selection of mine.
:::
